site_name: Run Scanner
theme: readthedocs
site_url: https://miso-lims.github.io/runscanner/
site_description: Run Scanner Documentation
site_author: Genome Sequence Informatics, Ontario Institute for Cancer Research

repo_url: https://github.com/miso-lims/runscanner

nav:
    - About : index.md
    - Getting Started:
        - Installation and Setup : installation.md
        - Illumina setup : illuminasetup.md
        - Monitoring with Prometheus : prometheus.md
    - Pages:
        - Main : main.md
        - Scanned : scanned.md
        - Scheduled : scheduled.md
        - Processing : processing.md
        - Unreadable : unreadable.md
        - API Docs : api.md
    - Troubleshooting : troubleshooting.md
    - Appendices : appendices.md
