{
 "title": "Run Scanner",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Epoch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "miso_runscanner_epoch", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Configuration (Timestamp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_configuration_timestamp",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Runs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Runs Scanned",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_errors",
     "legendFormat": "Errors {{instance}}/{{platform}}"
    },
    {
     "expr": "miso_runscanner_new_runs_scanned",
     "legendFormat": "New {{instance}}"
    }
   ]
  },
  {
   "title": "Bad Directories",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_directories_attempted - miso_runscanner_directories_accepted",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "runscanner.res.oicr.on.ca JVM memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"runscanner.res.oicr.on.ca:8080\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Scan Timestamp (Client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_client_scan_timestamp",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Client Processing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_client_run_count",
     "legendFormat": "{{instance}} Processed"
    },
    {
     "expr": "miso_runscanner_client_save_errors",
     "legendFormat": "{{instance}} Failed"
    },
    {
     "expr": "miso_runscanner_client_save_new",
     "legendFormat": "{{instance}} New"
    },
    {
     "expr": "miso_runscanner_client_save_update",
     "legendFormat": "{{instance}} Update"
    }
   ]
  },
  {
   "title": "Server Errors (Client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_client_read_errors",
     "legendFormat": "{{instance}}[{{url}}]"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Current Progress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_processing_runs",
     "legendFormat": "{{instance}}/{{platform}} Processing"
    },
    {
     "expr": "miso_runscanner_waiting_runs",
     "legendFormat": "{{instance}}/{{platform}} Waiting"
    }
   ]
  },
  {
   "title": "Dropped Runs (Client)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miso_runscanner_client_bad_runs",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}